
GET http://localhost:3000/api/post
###

GET http://localhost:3000/api/post/4
###

GET http://localhost:3000/api/autor
###

GET http://localhost:3000/api/autor/1
###



POST http://localhost:3000/api/post
Content-Type: application/json

{
    "titulo": "tengo mucho sueño",
    "descripcion": "Enserio quiero dormir",
    "fecha_creacion": "2022-25-10",
    "categoria": "Terror",
    "autores_id": 1
}
###

POST http://localhost:3000/api/autor
Content-Type: application/json

{
    "nombre": "Nicolassd",
    "email": "mickj@gma",
    "imagen": "https://www.lanacion.com.ar/resizer/=/1920x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/JV74LZLLURFNHNUMV3SAWUHBPQ.JPG"
}
###



PUT http://localhost:3000/api/blog
###

DELETE http://localhost:3000/api/autor/26

###
DELETE http://localhost:3000/api/post/12

