
GET http://localhost:3000/api/post/16

###
GET http://localhost:3000/api/autor



###
POST http://localhost:3000/api/post
Content-Type: application/json

{
    "titulo": "tengo sueño hoy tambien",
    "descripcion": "Enserio quiero dormir",
    "fecha_creacion": "2022-02-10",
    "categoria": "Terror",
    "autores_id": 1
}


###
POST http://localhost:3000/api/autor
Content-Type: application/json

{
    "nombre": "Nicolassd",
    "email": "mickj@gma",
    "imagen": "https://www.lanacion.com.ar/resizer/=/1920x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/JV74LZLLURFNHNUMV3SAWUHBPQ.JPG"
}
###


###
PUT http://localhost:3000/api/post/16
Content-Type: application/json

{
  "titulo": "hace sueño",
  "descripcion": "Cassie Salazar es una joven que vive en un pequeño apartamento en ruinas. Diagnosticada con diabetes tipo 1 hace 6 meses, Cassie no tiene suficiente para cubrir la insulina. Puede pagar los medicamentos o pagar el alquiler, pero no ambos. Trabaja en un bar como mesera donde también realiza covers con su banda, The Loyal. Conoce a Luke Morrow por primera vez cuando un grupo de marines estadounidenses recién reclutados entra en el bar una noche. En ese grupo está Frankie, el amigo de la infancia de Cassie. Comienzan a ponerse al día cuando sus amigos comienzan a hacer bromas misóginas hacia Cassie. Ella les dispara antes de alejarse. Luke intenta hacer las paces, lo que finalmente falla ya que los dos tienen mentalidades muy opuestas.",
  "fecha_creacion": "2022-07-29",
  "categoria": "Romance",
  "autores_id": 1
}


###
PUT http://localhost:3000/api/autor/19
Content-Type: application/json

{
  "nombre": "Mick",
  "email": "jacksoj@outlook.com",
  "imagen": "https://www.lanacion.com.ar/resizer/0y2qJGiQTxhCVIb6ak5f8DUDotQ=/1920x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/JV74LZLLURFNHNUMV3SAWUHBPQ.JPG"
}


###
DELETE http://localhost:3000/api/post/16

###
DELETE http://localhost:3000/api/autor/19





